name: Tests

on: [push]

jobs:
  bionic:
    strategy:
      fail-fast: false
      matrix:
        runner: ['swift:5.2-xenial', 'swift:5.2-bionic']

        include:
          - installcmd: 'apt-get -q update && apt-get -q install -y libsqlite3-dev'
    container: ${{ matrix.runner }}
        
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
