name: Tests

on: [push]

jobs:
  bionic:
    services:
      sqlite:
       image: keinos/sqlite3
    container: 
      image: vapor/swift:5.2-bionic
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
